#ifndef SL_SHARED_STANDARD_H
#define SL_SHARED_STANDARD_H

// Uniform buffer
#define SL_BINDING_POINT_CAMERA 0

// Texture
#define SL_SLOT_ALBEDO 0
#define SL_SLOT_NORMAL 1
#define SL_SLOT_ORM 2
#define SL_SLOT_EMISSIVE 3

// Model mat
#define SL_LOCATION_MODEL 0
#define SL_LOCATION_MODEL_INV_TRANS 1

// Albedo
#define SL_LOCATION_ALBEDO_USE_TEXTURE 2
#define SL_LOCATION_ALBEDO_FACTOR 3
#define SL_LOCATION_ALBEDO_TILLING 4

// Normal
#define SL_LOCATION_NORMAL_USE_TEXTURE 5
#define SL_LOCATION_NORMAL_FACTOR 6
#define SL_LOCATION_NORMAL_TILLING 7

// Occlution
#define SL_LOCATION_OCCLUSION_USE_TEXTURE 8
#define SL_LOCATION_OCCLUSION_FACTOR 9
#define SL_LOCATION_OCCLUSION_TILLING 10

// Roughness
#define SL_LOCATION_ROUGHNESS_USE_TEXTURE 11
#define SL_LOCATION_ROUGHNESS_FACTOR 12
#define SL_LOCATION_ROUGHNESS_TILLING 13

// Metallic
#define SL_LOCATION_METALLIC_USE_TEXTURE 14
#define SL_LOCATION_METALLIC_FACTOR 15
#define SL_LOCATION_METALLIC_TILLING 16

// Emissive
#define SL_LOCATION_EMISSIVE_USE_TEXTURE 17
#define SL_LOCATION_EMISSIVE_FACTOR 18
#define SL_LOCATION_EMISSIVE_TILLING 19

#endif
