#ifndef SL_SHARED_TONEMAPPING_H
#define SL_SHARED_TONEMAPPING_H

#define SL_TONEMAPPING_CLAMP 0
#define SL_TONEMAPPING_REINHARD 1
#define SL_TONEMAPPING_HABLEFILMIC 2
#define SL_TONEMAPPING_ACES 3
#define SL_TONEMAPPING_ACES_SIMPLE 4
#define SL_TONEMAPPING_PBRNEUTRAL 5

#endif
