#ifndef SL_SHARED_H
#define SL_SHARED_H

// Uniform buffer
#define SL_BINDING_POINT_CAMERA 0
#define SL_BINDING_POINT_LIGHT 1

// Texture
#define SL_SLOT_ALBEDO 0
#define SL_SLOT_NORMAL 1
#define SL_SLOT_ORM 2
#define SL_SLOT_EMISSIVE 3
#define SL_SLOT_RADIANCE 4
#define SL_SLOT_IRRADIANCE 5
#define SL_SLOT_IBL_LUT 6

// Model mat
#define SL_LOCATION_MODEL 0
#define SL_LOCATION_MODEL_INV_TRANS 1

// Material
#define SL_LOCATION_ALBEDO_USE_TEXTURE 2
#define SL_LOCATION_ALBEDO_FACTOR 3
#define SL_LOCATION_ALBEDO_TILLING 4
#define SL_LOCATION_NORMAL_USE_TEXTURE 5
#define SL_LOCATION_NORMAL_FACTOR 6
#define SL_LOCATION_NORMAL_TILLING 7
#define SL_LOCATION_OCCLUSION_USE_TEXTURE 8
#define SL_LOCATION_OCCLUSION_FACTOR 9
#define SL_LOCATION_OCCLUSION_TILLING 10
#define SL_LOCATION_ROUGHNESS_USE_TEXTURE 11
#define SL_LOCATION_ROUGHNESS_FACTOR 12
#define SL_LOCATION_ROUGHNESS_TILLING 13
#define SL_LOCATION_METALLIC_USE_TEXTURE 14
#define SL_LOCATION_METALLIC_FACTOR 15
#define SL_LOCATION_METALLIC_TILLING 16
#define SL_LOCATION_EMISSIVE_USE_TEXTURE 17
#define SL_LOCATION_EMISSIVE_FACTOR 18
#define SL_LOCATION_EMISSIVE_TILLING 19
#define SL_LOCATION_RENDERING_MODE 20
#define SL_LOCATION_ALPHA_CUTOFF 21

// Sky
#define SL_LOCATION_SKY_FACTOR 22
#define SL_LOCATION_IBL_FACTOR 23

// Tonemapping
#define SL_TYPE_TONEMAPPING_CLAMP 0
#define SL_TYPE_TONEMAPPING_REINHARD 1
#define SL_TYPE_TONEMAPPING_HABLEFILMIC 2
#define SL_TYPE_TONEMAPPING_ACES 3
#define SL_TYPE_TONEMAPPING_ACES_SIMPLE 4
#define SL_TYPE_TONEMAPPING_PBRNEUTRAL 5

// Rendering mode
#define SL_TYPE_RENDERING_MODE_OPAQUE 0
#define SL_TYPE_RENDERING_MODE_CUTOUT 1
#define SL_TYPE_RENDERING_MODE_TRANSPARENT 2

// Light
#define SL_LIGHT_MAX_COUNT 128
#define SL_TYPE_LIGHT_DIRECTIONAL 0
#define SL_TYPE_LIGHT_POINT 1
#define SL_TYPE_LIGHT_SPOT 2

struct SL_LightUniformBuffer
{
    int type;
    float intensity;
    float range;
    float scale;
    float offset;
    float colorR, colorG, colorB;
    float positionX, positionY, positionZ;
    float directionX, directionY, directionZ;
    float padding0, padding1;
};

#endif
