#pragma once

// Copy from SDL_mouse.h

#define SL_MOUSE_BUTTON_LEFT    1
#define SL_MOUSE_BUTTON_MIDDLE  2
#define SL_MOUSE_BUTTON_RIGHT   3
#define SL_MOUSE_BUTTON_X1      4
#define SL_MOUSE_BUTTON_X2      5

#define SL_MOUSE_BUTTON_MASK(X) (1u << ((X)-1))
#define SL_MOUSE_BUTTON_LMASK   SL_MOUSE_BUTTON_MASK(SL_MOUSE_BUTTON_LEFT)
#define SL_MOUSE_BUTTON_MMASK   SL_MOUSE_BUTTON_MASK(SL_MOUSE_BUTTON_MIDDLE)
#define SL_MOUSE_BUTTON_RMASK   SL_MOUSE_BUTTON_MASK(SL_MOUSE_BUTTON_RIGHT)
#define SL_MOUSE_BUTTON_X1MASK  SL_MOUSE_BUTTON_MASK(SL_MOUSE_BUTTON_X1)
#define SL_MOUSE_BUTTON_X2MASK  SL_MOUSE_BUTTON_MASK(SL_MOUSE_BUTTON_X2)
