#pragma once

// Copy from SDL_mouse.h

#define SL_BUTTON_LEFT    1
#define SL_BUTTON_MIDDLE  2
#define SL_BUTTON_RIGHT   3
#define SL_BUTTON_X1      4
#define SL_BUTTON_X2      5

#define SL_BUTTON_MASK(X) (1u << ((X)-1))
#define SL_BUTTON_LMASK   SL_BUTTON_MASK(SL_BUTTON_LEFT)
#define SL_BUTTON_MMASK   SL_BUTTON_MASK(SL_BUTTON_MIDDLE)
#define SL_BUTTON_RMASK   SL_BUTTON_MASK(SL_BUTTON_RIGHT)
#define SL_BUTTON_X1MASK  SL_BUTTON_MASK(SL_BUTTON_X1)
#define SL_BUTTON_X2MASK  SL_BUTTON_MASK(SL_BUTTON_X2)
