name: MSBuild

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2025

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Third parties, engine solution and resources
      run: ${{github.workspace}}/Setup.bat

    - name: Build Debug x64
      run: msbuild ${{github.workspace}}/SlamEngine.sln /p:Configuration=Debug /p:Platform=x64

    - name: Build Release x64
      run: msbuild ${{github.workspace}}/SlamEngine.sln /p:Configuration=Release /p:Platform=x64

    - name: Build Final x64
      run: msbuild ${{github.workspace}}/SlamEngine.sln /p:Configuration=Final /p:Platform=x64
